### ISSUE TITLE
Mobile view - when scrolling > the parent view scrolls and not the workflow editor view

### ISSUE THREAD

**Issue by trapacska** [bitrise-io/bitrise-workflow-editor#141]

**Comment by erosdome** [comment]
This has been fixed with the new release to the website.

**Comment by erosdome** [comment]
Reopened, still an issue on mobile Safari.

**Comment by fwigorcferreira** [comment]
This bug was seem on:

```
iPhone X
iOS 11.4
Date: 06/07/2018
```

**Comment by kkk669** [comment]
I’ve seen the first time on:

```
iPad Pro 12.9-inch 2nd generation
iOS 11.1
Date: November 12, 2017
```

and it still happens on:

```
iPad Pro 12.9-inch 2nd generation
iOS 12 beta 4
Date: July 20, 2018
```

**Comment by kkk669** [comment]
@erosdome Why did you close this issue? It’s not resolved and makes the workflow editor unusable on iOS.

video: https://youtu.be/WKbOzVR9G3w

**Comment by fwigorcferreira** [comment]
@erosdome I agree with @kkk669 

This issue was closed, but the bug was not solved. It still happens on:

```
iPhone X
iOS 11.4

iPhone 6
iOS 11.0.1

iPhone 6s
iOS 10.3
```

Tested with the latest version available on this repository.

**Comment by dbreuer** [comment]
@trapacska @fwigorcferreira 

We released some improvement which should fix the bug #2 scrolling issue on mobile Safari. Tested on iPhone X and iPhone 6s with IOS 11.4.1. 
Thank you for you help.

**Comment by fwigorcferreira** [comment]
@dbreuer I tested with the latest version `v1.1.24` and the bug is not solved! Problem still happening!

**Comment by fwigorcferreira** [comment]
@dbreuer As I put on the issue #313, in the website thread, and sent to the client support chat, this bug was seem on version v1.1.24, on:

```
iPhone X
iOS 11.4

iPhone 6
iOS 11.0.1

iPhone 6s
iOS 10.3
```

https://www.dropbox.com/s/q7w3woe6rdq1eor/scroll_problem.MP4?dl=0

Also tested using "offline" version. Same issues.

**Comment by fwigorcferreira** [comment]
@dbreuer I just run some tests, and there are still problems on scrolling contents:

https://www.dropbox.com/s/vz0kgl16j5oj5fu/IMG_1212.TRIM.MOV?dl=0

Tested on:

```
iPhone X
iOS 11.4

iPhone 7 Plus
iOS 11.1.1
```
